[build-system]
requires = ["setuptools>=61.0.0", "Cython>=3.0.0", "numpy>=2.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pcv_voxel_downsample"
version = "1.2.0"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
dependencies = [
    "numpy>=2.0.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["pcv_voxel_downsample"]

[tool.cibuildwheel]
build = "cp311-* cp313-*"
